package io.lazaro.pathguide

import android.graphics.Bitmap

data class PathGuideDebugState(
    val frame: Bitmap,
    val frameWidth: Int,
    val frameHeight: Int,
    val mode: PathGuideMode,
    val corridor: CorridorState,
    val doorwayPhase: DoorwayGuidePhase = DoorwayGuidePhase.IDLE,
    val stairState: StairState,
    val handrailSide: HandrailSide,
    val lastLabel: String? = null,
    val lastSceneDescription: String? = null,
    val turnRemainingDeg: Float? = null,
    val turnTurnedDeg: Float? = null,
    val brainPhase: ExitBrainPhase = ExitBrainPhase.EXPLORE,
    val junctionType: JunctionType = JunctionType.NONE,
    val approachState: ApproachState = ApproachState(),
    val outdoorPhase: OutdoorNavPhase? = null,
    val roadSide: RoadSide = RoadSide.UNKNOWN,
    val safeSide: RoadSide = RoadSide.UNKNOWN,
    val sidewalkAlignment: SidewalkAlignment = SidewalkAlignment.UNKNOWN,
    val driftScore: Float = 0f,
    val centeringScore: Float = 0.5f,
    val inSafeZone: Boolean = false,
    val guideLeftBeep: Float = 0f,
    val guideRightBeep: Float = 0f,
    val sidewalkLeftNorm: Float = 0.22f,
    val sidewalkRightNorm: Float = 0.78f,
    val mapsInstructionType: MapsInstructionType = MapsInstructionType.OTHER,
    val stairPeaks: Int = 0,
    val routeMatchConfidence: Float? = null,
    val routeLateralOffsetM: Float? = null,
    val routeInReplaySegment: Boolean = false,
    val routeExpectedLeftP: Float? = null,
    val routeExpectedRightP: Float? = null,
    val lateralOffsetNorm: Float = 0f,
    val walkableConfidence: Float = 0f,
    val perceptionSource: PerceptionSource = PerceptionSource.MONOCULAR,
    val frontalDistanceM: Float? = null,
    val updatedAtMs: Long = System.currentTimeMillis(),
)
